### ISSUE TITLE
Remove `Section.code` field

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#1305]
@jaburgoyne , the `Section` object contains a `code` field, which is populated with a random integer between 0 and 99999. Do you remember what the purpose of this code was? Do you think it's still necessary? The only use I could think of was that it makes it harder to infer the link of a section, but it's also rather hard to guess the id (by which it is otherwise retrieved), and ids are unique.

**Comment by jaburgoyne** [comment]
I don't remember exactly, but I think it indeed had to do with some kind of mild security by obscurity. We were quite worried about potential geofencing requirements for a time, but licensing turned out to be easier than we expected. 

Please check that this field is not used anywhere, but if it is not, you are free to get rid of it as far as I am concerned.
