### ISSUE TITLE
[TMS] Sound not working

### ISSUE THREAD

**Issue by jaburgoyne** [Amsterdam-Music-Lab/MUSCLE#628]
Vanderbilt has just reported that *no* fragments are playing sound in That's My Song. I cannot reproduce the issue myself but have not tested fully with VPNs, etc. Their location is Nashville, Tennessee, and they access the experiment using iPads.

They would like to be able to run a session again today: is it possible to have a look?

**Comment by tanguy-rdm** [comment]
Hi all !

Thanks a lot for being so responsive in trying to help! Indeed, I reviewed your troubleshooting steps and those seem to be a great starting point !!

On Vanderbilt side, the team realized that the bug might be associated with an incompatibility between the game and the iOS version of the iPAD used to run the game. From what we know, sound was failing when our iOS was around 16.6 (i.e., prior to update). Facing the sound issues, we decided to update our iPads to the most recent available version (17.1.2.) and now the game seems to work just fine !

With this in mind, I have two remarks:
(1) Do you think it is plausible that the game might be only compatible with specific iOS versions? 
(2) If this is the case, would there be an option for the game's programmers to adjust this and extend the compatibility to a wider range of iOS versions? I am asking this specifically because, in the long run, we (as a lab) might not be able to control which iOS version participants will use to run the game. 

Again thanks for the help !

**Comment by BeritJanssen** [comment]
Thanks for the remark about iOS versions. Indeed, I just found this post which seems to clarify the issue, and why the update fixes this:
https://devcodef1.com/news/1068842/fixing-ios-17-web-audio-issue
We are using webAudio, and there's been a faulty implementation for that in iOS. I'll investigate in how far we can implement the workaround suggested in the post to assure participants with older iOS versions don't face issues.

**Comment by Evert-R** [comment]
I have made a pull request with the solution offered in that post.
The PR can be discarded if it doesn't fix the ios17 issue.

**Comment by Evert-R** [comment]
This soulution is now running on the acceptance server:
https://acc.amsterdammusiclab.nl/thats_my_song

**Comment by BeritJanssen** [comment]
The solution for closing and opening the audioContext does not seem to fix the problem across systems. Alternatively, we could do the following:
- determine the user's system (using `window.navigator.userAgent`)
- if the system contains "OS {majorversion_minorversion} like Mac OS X" and `majorversion<17.0`, disable webAudio

**Comment by jaburgoyne** [comment]
I just want to bump this issue, because perhaps we can close it. So far as I know, there have been no problems at Vanderbilt since they upgraded their OS. In preparation for a full online roll-out, however, they have asked for language about exactly which OS versions and devices are supported. Do we know now whether there are any major OS releases in the wild – major in the sense that a substantial portion of users will *not* at this point have received an automatic update – where this WebAudio bug is still active?
