### ISSUE TITLE
Keep "focus" on buttons when handling a form with multiple elements

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#656]
In the Music Preferences experiment, we have a form composed of a ButtonArray and an IconRange component. After selecting a button, when interacting with the slider, the selected button loses focus:

https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/11174072/f28a4bfd-e563-433e-b11e-be73fedfa4af

It would be clearer for participants if they kept the visual feedback from the first choice they made.

**Comment by drikusroor** [comment]
I think we shouldn't keep it in "focus" in the html semantics meaning of the word, because that would mean:

> The focused element is the element that will receive keyboard and similar events by default.

Source: [Mozilla](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus)

Which isn't the case, because the user has already moved on to the range slider input. Once it touches the range slider element, that element now has focus.

But yes, we should provide the user with information/feedback about the choice it made. Basically, we can compare it to a button group or radio buttons (but with different styling). Semantically, we therefore have to use the `checked` attribute to show the browser that the button is active/selected/chosen, and visually we can use a different color or border to make that clear.

**Comment by drikusroor** [comment]
Btw, where is this component located, or which specific props do I have to use to reproduce this? Perhaps I can already make a storybook story out of it. 😄
