### ISSUE TITLE
Reorganize color schemes in frontend

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#683]
Currently, we don't have an easy mechanism to set styles of playback buttons. It would be good to add different colour schemes easily.

Originally, colours were all set individually through the backend, which led to rather lengthy list of hex strings, which were difficult to read and reuse. This led to my idea to only send style classes (what's now "neutral", "boolean", etc.) and apply them through a whole `Trial`, so it would affect all the buttons in the associated form and playback. This had to be revisited when realizing that Trial can hold multiple questions, which may need different styling (i.e., the Musical Preferenes experiment). So the style is now applied *per question*, and the style classes are not send or set for the playback buttons at all. What makes the Playbuttons slightly more complex is that they use mixins for styling, as the shadow around them is also a shade of their primary colour.

This issue may be more of a "design" one: how to make sure colours can be set with a small effort, in a file that's easy to find, and so that the choices we have now set for different colour schemes can be overridden easily by other teams using the infrastructure?

**Comment by drikusroor** [comment]
I've been thinking about and experimenting with this a bit in the last couple of days, and I've com to the conclusion that I think we first need an overview of the possible color schemes and variations for the components that we have or that we want to have.

But based on my interpretation of what you are describing I've had something in mind:

* We (the MUSCLE team) decide which color tokens (primary, secondary, warning, danger, etc.) and color schemes (boolean, neutral, boolean-inverted, neutral-inverted, etc.) exist. Users that clone and self-host this platform can optionally alter the colors in the color tokens and color schemes.
* The self-hosting user can select a default color scheme for the whole platform. (optional)
* The user who designs / programs an experiment can select a default color scheme for the experiment.
* The user who designs / programs an experiment can select a color scheme for every question / trial of an experiment, by supplying the color scheme class as a question / trial configuration parameter.
* For trials that use multiple components, I was thinking of using some form of nested configuration with a fallback to the parent class. In that way we can give the user full control over the color scheme to use per component.
* The trial component needs to take this into account and be able to pass nested color scheme configurations to its children.
* All components need to be able to handle the color schemes that we (the MUSCLE team) have defined and have a prop for this. Some components will probably need their own interpretation of a color scheme instead of simply relying on a globally defined button style mixin.

An example of how to approach this in pseudo-code:

## Backend / Experiment configuration

Global color scheme: `boolean`

```
Experiment A
  Question:
    text: What is your age?
    colorScheme:
      root: boolean-inverted
  Question:
    text: How many languages do you speak?
    colorScheme:
      root: neutral-inverted
  Trial:
    type: EXPLAINER
    colorScheme:
      root: neutral
      submitButton:
        root: boolean
```

## Trial component

```jsx
const Trial = ({ type, colorScheme = { root: 'boolean' }}) {
  switch (type) {
    case "EXPLAINER":
      return <Explainer colorScheme={colorScheme} />
    default:
      return <p>Unknown view</p>
}
```

```scss
.trial {
  &.neutral {
    // do neutral styles
  }
}
```

## Explainer component

```jsx
const Explainer = ({ colorScheme = { root: 'boolean' }}) {
  return (
    <div className={colorScheme.root}>
      <p>Text that explains things</p>
      <Button type="submit" colorScheme={colorScheme.submitButton || colorScheme.root}>
        Submit
      </Button>
    </div>
  )
}
```

```scss
.trial {
  &.neutral {
    // do neutral styles
  }
}
```

## Button

```jsx
const Button = ({ colorScheme = { root: 'boolean' }}) {
  return (
   <button type="submit" colorScheme={colorScheme.root}>
      Submit
    </button>
  )
}
```

```scss
.trial {
  &.neutral {
    // do neutral styles
  }

  &.boolean {
    // do boolean styles
  }
}
```
