### ISSUE TITLE
Import modules in `experiment.rules` automatically

### ISSUE THREAD

**Issue by BeritJanssen** [Amsterdam-Music-Lab/MUSCLE#732]
**Is your feature request related to a problem? Please describe.**
Right now, a lot of bookkeeping is needed in order to add a new rules file: next to the file itself, we also need to update `experiment.rules.__init__.py`.

**Describe the solution you'd like**
We might walk over the submodules of `rules` and add them to the `__all__` object, and use that over the custom dict in the selection of rules in `experiment.admin`, see: https://stackoverflow.com/questions/3365740/how-to-import-all-submodules

## Important ⚠️

Please remember to remove the rules registration logic from #735 ❗️

**Comment by albertas-jn** [comment]
I think the main issue here is `EXPERIMENT_RULES` in `experiment/rules/__init__.py`. We would still need to manually edit this dictionary,  because experiment ID strings are not the same as the names of the corresponding classes. So I am not sure if automatic importing of rules modules is worth doing.

**Comment by BeritJanssen** [comment]
Hm, perhaps this is not worth it then indeed. Obviously, we should get rid of the ugly `EXPERIMENT_RULES` construct (see also #330 ), and write a method in `__init__.py` which automatically imports the `__repr__` or `__init__` methods from the rules into a dict. I think that at least should be doable.
