### ISSUE TITLE
'Who's Got Rhythm?' experiment stuck

### ISSUE THREAD

**Issue by MarielleBaelemans** [Amsterdam-Music-Lab/MUSCLE#861]
The 'Who's got Rhythm?' experiment get's stuck after the listening instructions. It happens in Chrome, Firefox, and Edge. The test simply does not start after the introduction questions (headphones, quiet room). See attached screenshot 
I would like to see the rhythm experiments running smoothly again, since there is quite a lot of animo for it after Henkjan's University of the Netherlands video. 

![Screenshot 2024-03-15 104129](https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/47387569/27cea5da-1847-41b5-a9d5-7ee774d7225b)

## How to reproduce:

_Note: I, Drikus, added these reproduce steps but I'm not even sure if we are talking about this experiment._

- Navigate to https://app.amsterdammusiclab.nl/rhythm_september_inactive (temporary slug as we are using the `rhythm_september` slug for `DurationDiscrimination` temporarily)
- Click through the instructions until you reach the `ListeningConditions` experiment (slug `/lisc`) that is designed to test whether you can play and hear the audio.
- Finish the `ListeningConditions` experiment.
- You won't be redirected to one of the next experiments that would normally picked randomly from a list. See also the [RhythmTestSeries](https://app.amsterdammusiclab.nl/admin/experiment/experimentseries/1/change/) experiment collection.

## Expected behavior

Finishing the `ListeningConditions` experiment in the `RhythmTestSeries` experiment collection _should_ redirect you to one of the randomly picked experiments as defined here https://app.amsterdammusiclab.nl/admin/experiment/experimentseries/1/change/

**Comment by jaburgoyne** [comment]
@BeritJanssen @drikusroor @albertas-jn @Evert-R: Could any of you have a look at this today? Press excitement is usually short-lived, and so it's important that people are seeing things working correctly ASAP

**Comment by Evert-R** [comment]
I found a bug in the experiment series, but after fixing this the rhythm serie still doesn't work. (As well as other single rhytm experiments.) Before fixing this bug I couldn't open the experiment series in the admin interface.

The slug for the link on the website for the rhythm experiments is `lisc` which points to the listening conditions. (a single 'experiment')
As a workaround I have now changed the slug of the Tone Duration Dicrimination to `lisc` so that the link on the website at least points to a working experiment, untill this is resolved.

**Comment by Evert-R** [comment]
The experiment series isn't working. I found a bug in the admin form on the `main` branch. After fixing that I could open the experiment series in the admin again, but the rhythm series still don't work. As well as several single rhythm experiments.

The interval duration discrimination experiment does work, so I changed that slug to `rhythm_september`, (this was `ddi`) so that at least there is a working link to a single rhythm experiment on the website untill this is resolved. Not ideal ofcourse.

**Comment by jaburgoyne** [comment]
Thanks for the temporary hot fix! But yes, let's try to get to the bottom of the overall regression as soon as we can

**Comment by hhoning** [comment]
Indeed, thanks for the quick fix... the peak of the media attention has passed (cf. UvN, ad.nl and nu.nl)

**Comment by BeritJanssen** [comment]
Fixed as of the latest release.
