### ISSUE TITLE
[Congo Matching Pair Quality Control] Data included all the variables we need

### ISSUE THREAD

**Issue by Lia-JX-Li** [Amsterdam-Music-Lab/MUSCLE#986]
As a result of the meeting with Henkjan and Ashley on 30.04. We decided that JL will file the most important three aspects to be tested/quality checked by the MUSCLE team before delivering the product. 
Please feel free to close the issue after you have checked it in the code.

Third aspect:
This aspect is data recording related. The software should record all the variables / data needed for later analysis. Please take the following move_table as an example, this is the dataframe we used for ICMPC matching pairs data analysis. 

And of course, now Evert has added the time interval between clicks to it, so this is an extra variable that this move_table not yet have. 

<img width="1001" alt="Screenshot 2024-04-30 at 10 01 36 PM" src="https://github.com/Amsterdam-Music-Lab/MUSCLE/assets/65351308/8a24e2bc-7f8c-4696-b316-7f4d078a301c">

**Comment by Evert-R** [comment]
All these variables are recorded in the results. `cardIndex` is now board_position, so 1-16, instead of 0-15.
The timestamp is a rising number in milliseconds, with a precision of microseconds, that starts running once the game is loaded.
The response_interval_ms is calculated from these timestamps, rounded to whole milliseconds.
So basically you can also calculate the interval between each turn, and every move.
